config/routes.rb
CraigslistRails::Application.routes.draw do
  root to: 'categories#index'

  resources :categories do 
    resources :posts
  end

end

# get '/categories' => 'categories#index'
# /category/:category_id/posts
# /category/auto/posts/blue-nissan-versa-24 #slug (gem to create slug)

# /posts/24

# /category/furniture/posts

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :posts

  # def to_param
  #   slug
  # end

  # def name=(_name)
  #   slug = name.downcase
  # end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :price, :category_id

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  # def show
  #   @category = Category.find_by_slug(params[:id])
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :get_category, only: [:new, :edit, :create]
  before_filter :get_post, only: [:show, :edit, :update, :destroy]
  
  def get_category
    @category = Category.find(params[:category_id])
  end

  def get_post
    @post = Post.find(params[:id])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = @category.posts.create(params[:post])
    redirect_to category_post_path(@post.category, @post)
  end

  def edit
  end

  def update
    @post.update_attributes(params[:post])
    redirect_to category_post_path(@post.category, @post)
  end

  def destroy
    @post.destroy
    redirect_to root_url, notice: "Successfully deleted '#{@post.title}'"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>Rails CraigsList</h1>
<h2>Categories</h2>
<% @categories.each do |category| %>
	<%= div_for category do %>
  <p><%= link_to category.name, category %></p>
	<% end %>
<% end %>

<!-- div_for adds each category to the div="category" where the id="category_id" - this helps in the future when you're working with the DOM doing jQuery and AJAX -->

<% if flash[:notice] %>
  <p class="flash-notice"><%= flash[:notice] %></p>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<% @category.posts.each do |post| %>
  <%= div_for post do %>
  	<p><%= link_to post.title, category_post_path(post.category, post) %></p>
  <% end %>
<% end %>


<%= link_to "Home", root_path %> |
<%= link_to "New Posting", new_category_post_path(@category) %>

app/views/layouts/_post_form.html.erb
<%= form_for ([@category, @post]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
   <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
   <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post<small>(<%= @category.name %>)</small></h2>
<%= render "shared/post_form", :locals => {post: @post, category: @category} %>
<%= link_to "Category Home", @category %>

app/views/posts/new.html.erb
<h2>Create New Post <small>(<%= @category.name %>)</small></h2>
<%= render "shared/post_form", :locals => {post: @post, category: @category} %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= number_to_currency(@post.price) %></p>
<p><%= @post.body %></p>

<%= link_to "Category Home", @post.category %> |
<%= link_to "Edit", edit_category_post_path(@post.category)%> |
<%= link_to "Delete", [@post.category, @post], method: :delete %>

app/views/shared/_post_form.html.erb
<%= form_for ([@category, @post]) do |f| %>
  <%= hidden_field(:post, :category_id, value: @category.id) %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
   <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
   <p>
    <%= f.submit %>
  </p>
<% end %>